### ISSUE TITLE
Endpoint GET `/books`

### ISSUE THREAD

**Issue by Adeynack** [Adeynack/finances-service-go#7]
depends on #6 
depends on #8 

# Use Cases

As a user
I want to get all the books that belong to me

As an administrator
I want to get all the books that exist in the system

# Tasks

- [x] create OpenAPI YAML document for describing the API
- [x] create `BooksController`
- [x] create endpoint `GET /books`
- [x] if query `list_all=true` & user has the `ADMIN` global right: return all books; otherwise, 403
- [x] return all books for which the current user has permission.
